### ISSUE TITLE
make data-mesh is failing

### ISSUE THREAD

**Issue by raghanag** [confluentinc/data-mesh-demo#68]
Hi @krisajenkins The command `make data-mesh` command is failing with the below error.

```
Kafka cluster id is empty
ERROR: Could not create cluster. Please troubleshoot.
make: *** [data-mesh] Error 1
```
Please note that I have entered billing details and successfully logged into the cloud using credentials.

**Comment by rspurgeon** [comment]
@raghanag thank you for filing this issue. I should be able to post a fix for this by tomorrow. Apologies for the issue you experienced. In the meantime you may want to remove any 'abandoned' resources in your cloud account created by the data mesh script. In particular look for environments ending in `-data-mesh-demo` and please be sure to apply the promotion code `DATAMESH200` to your account to recoup any costs for running this demo.  I'll reply here once the fix is applied.

**Comment by raghanag** [comment]
@rspurgeon the promo code `DATAMESH200` is giving the below error, do you mind if you can please verify. 
![image](https://user-images.githubusercontent.com/11847063/155220039-1ebca868-d2f8-480f-bc9b-8d5dbec8188c.png)

**Comment by rspurgeon** [comment]
@raghanag I pushed a fix that should work for you (I just built a data mesh prototype from the updated script), but please let me know if you experience other issues.  Also, I'm trying to figure out why that promotion code isn't working for you.  Another option is `DATAMESH101` if you'd like to try that one.  Thanks for trying out the prototype
